// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Zqzkpud4y3j2coyJECQQ_wo331CCPAg',
    appId: '1:170108110737:web:60763a5798c212ec3cfc30',
    messagingSenderId: '170108110737',
    projectId: 'utara-drive',
    authDomain: 'utara-drive.firebaseapp.com',
    storageBucket: 'utara-drive.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0KhnOkaT1aB3RfiH0q54ZtAffkGtXUs',
    appId: '1:170108110737:android:a9f5a132bf687fe53cfc30',
    messagingSenderId: '170108110737',
    projectId: 'utara-drive',
    storageBucket: 'utara-drive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA59dJtLqLGuAgqlvNMW8OCJVtUlMeZthM',
    appId: '1:170108110737:ios:a2e6f576c8c1fb653cfc30',
    messagingSenderId: '170108110737',
    projectId: 'utara-drive',
    storageBucket: 'utara-drive.appspot.com',
    androidClientId: '170108110737-rahjsqnk4d0fkee1h89nisr0r6vtpqep.apps.googleusercontent.com',
    iosClientId: '170108110737-a8u32nfqupifodiorumjpje88t5ie4bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.utaraDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA59dJtLqLGuAgqlvNMW8OCJVtUlMeZthM',
    appId: '1:170108110737:ios:a2e6f576c8c1fb653cfc30',
    messagingSenderId: '170108110737',
    projectId: 'utara-drive',
    storageBucket: 'utara-drive.appspot.com',
    androidClientId: '170108110737-rahjsqnk4d0fkee1h89nisr0r6vtpqep.apps.googleusercontent.com',
    iosClientId: '170108110737-a8u32nfqupifodiorumjpje88t5ie4bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.utaraDrive',
  );
}
